version: "3"
services:
   outward-ct-service:
    image: outward-ct-service
    environment:
     - "FOO=BAR"
    ports:
      - 1234:1234
    volumes:
          - /data/out:/data/in
          - /data/part/out:/data/part/in
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
